2021-12-23 20:08:37,324 ERROR: Exception on /snip [GET] [in /home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: snip.timestamp

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/corey/Documents/Development/snippet/app/routes.py", line 121, in snip
    return render_template('snip.html', title="Snippets", snips=snips)
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/corey/Documents/Development/snippet/app/templates/snip.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/corey/Documents/Development/snippet/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block 'body'
    {% block content -%}
  File "/home/corey/Documents/Development/snippet/app/templates/base.html", line 56, in block 'content'
    {% block app_content %}{% endblock %}
  File "/home/corey/Documents/Development/snippet/app/templates/snip.html", line 7, in block 'app_content'
    {% for snip in snips %}
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2887, in __iter__
    return self._iter().__iter__()
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2894, in _iter
    result = self.session.execute(
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1692, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/home/corey/Documents/Development/snippet/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: snip.timestamp
[SQL: SELECT snip.id AS snip_id, snip.title AS snip_title, snip.description AS snip_description, snip.code AS snip_code, snip.timestamp AS snip_timestamp, snip.user_id AS snip_user_id 
FROM snip ORDER BY snip.timestamp DESC]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
